FROM docker.elastic.co/beats/filebeat:6.5.2

#RUN filebeat modules enable nginx
#RUN filebeat modules enable mysql

#COPY filebeat.yml /usr/share/filebeat/
#COPY nginx.yml /usr/share/filebeat/modules.d/
#COPY mysql.yml /usr/share/filebeat/modules.d/