services:
  app.admin.number:
    class: AppBundle\Admin\Number\NumberAdmin
    arguments:
      - ~
      - AppBundle\Entity\Number\Number
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'БезБахил в цифрах' }

  app.admin.question:
    class: AppBundle\Admin\Question\QuestionAdmin
    arguments:
      - ~
      - AppBundle\Entity\Question\Question
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'Вопрос-ответ' }

  main.admin.news:
    class: AppBundle\Admin\Common\NewsAdmin
    arguments: [~, %aw.news.entity_class%,~]
    tags:
      -  { name: sonata.admin, group: %aw.news.admin.group%, manager_type: orm, label: %aw.news.admin.label% }

  main.admin.article:
    class: AppBundle\Admin\Common\ArticleAdmin
    arguments: [~, %aw.article.entity_class%,~]
    tags:
      -  { name: sonata.admin, group: %aw.article.admin.group%, manager_type: orm, label: %aw.article.admin.label% }

  app.admin.menu_header:
    class: AppBundle\Admin\Menu\MenuHeaderAdmin
    arguments:
      - ~
      - AppBundle\Entity\Menu\MenuHeader
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'Меню шапки' }

  app.admin.menu_footer:
    class: AppBundle\Admin\Menu\MenuFooterAdmin
    arguments:
      - ~
      - AppBundle\Entity\Menu\MenuFooter
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'Меню футера' }

  main.admin.contact_us:
    class: AppBundle\Admin\ContactUs\ContactUsAdmin
    arguments: [~, 'AppBundle\Entity\ContactUs\ContactUs', ~]
    tags:
      -  { name: sonata.admin, manager_type: orm, group: 'messages', label: 'Сообщения "Написать нам"' }

  main.admin.region:
    class: AppBundle\Admin\Geo\RegionAdmin
    arguments: [~, 'AppBundle\Entity\Geo\Region', ~]
    tags:
      -  { name: sonata.admin, manager_type: orm, group: 'settings', label: 'Регионы' }

  main.admin.feedback:
    class: AppBundle\Admin\Feedback\FeedbackAdmin
    arguments: [~, 'AppBundle\Entity\Company\Feedback', 'AppBundle:Admin/Feedback/FeedbackAdmin']
    tags:
      -  { name: sonata.admin, manager_type: orm, group: 'text', label: 'Отзывы' }

  AppBundle\Admin\Common\EmailTemplateAdmin:
    decorates: aw_email_template_admin.email_template
    arguments:
      - null
      - %aw_email_template_admin.class%
      - SonataAdminBundle:CRUD
    tags:
      -
        name: sonata.admin
        manager_type: orm
        group: %aw_email_template_admin.email_template_group%
        label: %aw_email_template_admin.email_template_label%
        label_catalogue: PropelEmailTemplateAdminBundle
    calls:
      - [setModelManager, ['@aw_email_template_admin.model_manager'] ]
      - [setTemplate, [edit, AccuratewebEmailTemplateBundle:EmailTemplateAdmin:edit.html.twig]]
    public: true

  main.admin.organization:
    class: AppBundle\Admin\Organization\OrganizationAdmin
    arguments: [~, 'AppBundle\Entity\Organization\Organization', ~]
    tags:
      -  { name: sonata.admin, manager_type: orm, group: 'mo_cmo', label: 'Медицинские организации' }

  main.admin.organization_chief_medical_officer:
    class: AppBundle\Admin\Organization\ChiefMedicalOfficerAdmin
    arguments: [~, 'AppBundle\Entity\Organization\OrganizationChiefMedicalOfficer', ~]
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'mo_cmo', label: 'Глав.врач' }