services:
  app.admin.number:
    class: AppBundle\Admin\Number\NumberAdmin
    arguments:
      - ~
      - AppBundle\Entity\Number\Number
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'БезБахил в цифрах' }

  app.admin.question:
    class: AppBundle\Admin\Question\QuestionAdmin
    arguments:
      - ~
      - AppBundle\Entity\Question\Question
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'Вопрос-ответ' }

  main.admin.news:
    class: AppBundle\Admin\Common\NewsAdmin
    arguments: [~, %aw.news.entity_class%,~]
    tags:
      -  { name: sonata.admin, group: %aw.news.admin.group%, manager_type: orm, label: %aw.news.admin.label% }

  app.admin.menu_header:
    class: AppBundle\Admin\Menu\MenuHeaderAdmin
    arguments:
      - ~
      - AppBundle\Entity\Menu\MenuHeader
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'Верхнее меню (Header)' }

  app.admin.menu_footer:
    class: AppBundle\Admin\Menu\MenuFooterAdmin
    arguments:
      - ~
      - AppBundle\Entity\Menu\MenuFooter
      - PixSortableBehaviorBundle:SortableAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: 'main_page', label: 'Нижнее меню (Footer)' }