imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: admin.yml }
  - { resource: settings.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: "ru"
  aw.settings.admin.group: settings
  aw.settings.admin.label: Настройки

framework:
  #esi: ~
  #    translator:      { fallbacks: ["ru"] }
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer: { enable_annotations: true }
  default_locale: '%locale%'
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    name: SF_SESSID
  fragments: ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true
  templating:
    engines: ['twig']
  translator:
    fallbacks: ['%locale%']
    enabled: true
# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - 'Form/bezbahil_form_theme.html.twig'

# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8
    # if using pdo_sqlite as your database driver:
    #   1. add the path in parameters.yml
    #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
    #   2. Uncomment database_path in parameters.yml.dist
    #   3. Uncomment next line:
    #path: '%database_path%'
    server_version: 5.7
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: '%mailer_transport%'
  host: '%mailer_host%'
  username: '%mailer_user%'
  password: '%mailer_password%'
  port: '%mailer_port%'
  encryption: '%mailer_encryption%'
  spool: { type: memory }

sensio_framework_extra:
  router:
    annotations: false

stof_doctrine_extensions:
  default_locale: ru_RU
  orm:
    default:
      timestampable: true
      sortable: true

sonata_admin:
  title: Раздел администрирования
  dashboard:
    groups:
      main_page:
        label: Главная страница
      settings:
        label: Настройки
  options:
    html5_validate: false

sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]

sonata_doctrine_orm_admin:
  entity_manager: ~

sonata_core:
  form:
    mapping:
      enabled: false

stfalcon_tinymce:
  selector: ".tinymce"
  language: "ru"
  theme:
    simple:
      theme: "modern"
      height: '260px'
      plugins:
        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        - "insertdatetime media nonbreaking save table contextmenu directionality"
        - "emoticons template paste textcolor"
      toolbar1: "newdocument | insertfile undo redo | cut copy paste insert pastetext | print | searchreplace | visualchars"
      toolbar2: "styleselect  | formatselect | fontselect fontsizeselect | ltr rtl | bold italic underline strikethrough  removeformat subscript superscript | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
      toolbar3: "media image | link unlink | blockquote hr openlink charmap anchor | emoticons | nonbreaking | insertdatetime |pagebreak | spellchecker | code |  table | quote document "
      image_advtab: true

accurateweb_setting:
  configuration:
    class: AppBundle\Entity\Common\Setting