imports:
  - { resource: parameters.yml }
  - { resource: security.yml }
  - { resource: services.yml }
  - { resource: admin.yml }
  - { resource: settings.yml }
  - { resource: email_templates.yml }
  - { resource: sms_templates.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: "ru"
  aw.settings.admin.group: settings
  aw.settings.admin.label: Настройки
  aw.news.admin.group: text
  aw.news.admin.label: "Новости"
  aw.news.entity_class: AppBundle\Entity\Common\News
  aw.article.admin.group: text
  aw.article.admin.label: "Статьи"
  aw.article.entity_class: AppBundle\Entity\Common\Article
  aw_email_template_admin.class: AppBundle\Entity\Messaging\EmailTemplate
  aw_email_template_admin.email_template_group: settings
  aw_email_template_admin.email_template_label: Шаблоны писем
  aw.task_scheduler.background_job_repository: app.repository.backgorund_job
  aw.task_scheduler.uid:  bezbahil-background-job

framework:
  #esi: ~
  secret: '%secret%'
  router:
    resource: '%kernel.project_dir%/app/config/routing.yml'
    strict_requirements: ~
  form: ~
  csrf_protection: ~
  validation: { enable_annotations: true }
  #serializer: { enable_annotations: true }
  default_locale: '%locale%'
  trusted_hosts: ~
  session:
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    handler_id: session.handler.native_file
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    name: SF_SESSID
  fragments: ~
  http_method_override: true
  assets: ~
  php_errors:
    log: true
  templating:
    engines: ['twig']
  translator: { fallbacks: ['%locale%'] }

# Twig Configuration
twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - 'Form/bezbahil_form_theme.html.twig'
    - 'SonataCoreBundle:Form:datepicker.html.twig'
    - '@App/form/taxon_jstree_widget.html.twig'
#    - '@App/form/form.html.twig'

# Doctrine Configuration
doctrine:
  dbal:
    driver: pdo_mysql
    host: '%database_host%'
    port: '%database_port%'
    dbname: '%database_name%'
    user: '%database_user%'
    password: '%database_password%'
    charset: UTF8
    # if using pdo_sqlite as your database driver:
    #   1. add the path in parameters.yml
    #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
    #   2. Uncomment database_path in parameters.yml.dist
    #   3. Uncomment next line:
    #path: '%database_path%'
    server_version: 5.7
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
  transport: '%mailer_transport%'
  host: '%mailer_host%'
  username: '%mailer_user%'
  password: '%mailer_password%'
  port: '%mailer_port%'
  encryption: '%mailer_encryption%'

sensio_framework_extra:
  router:
    annotations: false

fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User\User
  from_email:
    address: "%mailer_from%"
    sender_name: "%mailer_sender_name%"
  registration:
    confirmation:
      enabled: true
    form:
      type: AppBundle\Form\Profile\RegistrationFormType
      validation_groups: [Default, RegistrationBezbahil]
  resetting:
    retry_ttl: 1800   # 30 минут
    token_ttl: 86400  # 24 часа

stof_doctrine_extensions:
  default_locale: ru_RU
  orm:
    default:
      timestampable: true
      sortable: true
      tree: true

sonata_admin:
  title: Раздел администрирования
  dashboard:
    groups:
      mo_cmo:
        label: МО и СМО
      disease:
        label: Справочник заболеваний
      main_page:
        label: Главная страница
      text:
        label: Текстовые разделы
      messages:
        label: Сообщения
      settings:
        label: Настройки
  options:
    html5_validate: false
  security:
    handler: sonata.admin.security.handler.role
    role_super_admin: ROLE_ADMIN

sonata_block:
  default_contexts: [cms]
  blocks:
    sonata.admin.block.admin_list:
      contexts: [admin]

sonata_doctrine_orm_admin:
  entity_manager: ~

sonata_core:
  form:
    mapping:
      enabled: true

stfalcon_tinymce:
  selector: ".tinymce"
  language: "ru"
  external_plugins:
    filemanager:
      url: "asset[fm/plugin.min.js]"
  theme:
    simple:
      theme: "modern"
      height: '400px'
      relative_urls: false
      convert_urls: false
      external_filemanager_path: '/fm/'
      plugins:
        - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
        - "searchreplace wordcount visualblocks visualchars code fullscreen"
        - "insertdatetime media nonbreaking save table contextmenu directionality"
        - "emoticons template paste textcolor"
      toolbar1: "newdocument | insertfile undo redo | cut copy paste insert pastetext | print | searchreplace | visualchars"
      toolbar2: "styleselect  | formatselect | fontselect fontsizeselect | ltr rtl | bold italic underline strikethrough  removeformat subscript superscript | forecolor backcolor | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent"
      toolbar3: "media image | link unlink | blockquote hr openlink charmap anchor | emoticons | nonbreaking | insertdatetime |pagebreak | spellchecker | code |  table | quote document "
      image_advtab: true
      filemanager_access_key: "83a2de51cdff498a8c68c04a44d49045"

accurateweb_application_settings_admin:
  configuration:
    class: AppBundle\Entity\Common\Setting

accurateweb_imaging:
  library: imagick

old_sound_rabbit_mq:
  connections:
    default:
      host:     '%rabbitmq_host%'
      port:     '%rabbitmq_port%'
      user:     '%rabbitmq_user%'
      password: '%rabbitmq_password%'
      vhost:    '%rabbitmq_project_vhost%'
  producers:
    obrashcheniya_emails:
      connection: default
      exchange_options:
        name: obrashcheniya_emails
        type: direct
    obrashcheniya_files:
      connection: default
      exchange_options:
        name: obrashcheniya_files
        type: direct
  consumers:
    obrashcheniya_emails:
      connection:       default
      exchange_options: {name: 'obrashcheniya_emails', type: direct}
      queue_options:    {name: 'obrashcheniya_emails'}
      callback:         obrashcheniya_emails_service
    obrashcheniya_files:
      connection:       default
      exchange_options: {name: 'obrashcheniya_files', type: direct}
      queue_options:    {name: 'obrashcheniya_files'}
      callback:         obrashcheniya_files_service