aw_email_templating:
  templating:
    loader: aw_email_templating.template.loader.doctrine
    entity: AppBundle\Entity\Messaging\EmailTemplate
  email_templates:
    email_contact_us:
      description: 'Обратная связь'
      variables:
        name: { description: "Имя" }
        email: { description: "Email" }
        text: { description: "Сообщение" }
      defaults:
        subject: "Обратная связь"
        body: |
          Пользователь по имени  %%name%% (с почтой %%email%%) решил связаться с администрацией . <br>
          Вопрос : %%text%% <br>

    email_feedback:
      description: 'Отзыв'
      variables:
        date: { description: "Дата" }
        url: { description: "Url на отзыв" }
      defaults:
        subject: "Отзыв"
        body: |
          О вашей компании оставили отзыв  %%date%% <br>
          Ссылка на страницу с  <a href ="%%url%%">отзывом</a>

    email_obrashcheniya_branch:
      description: 'Письмо с обращением в СМО'
      variables:
        author: { description: "Отправитель" }
      defaults:
        subject: "Обращение о взимании денежных средств"
        body: |
          На сайте bezbahil.ru было сформировано новое обращение от пользователя "%%author%%".

    appeal_sent_user:
      description: 'Уведомление пользователю о том, что его обращение отправлено в СМО'
      variables:
        author: { description: "Отправитель" }
        defaults:
          subject: "Ваше обращение о возврате денежных средств направлено в адрес страховой компании"
          body: |
            <div class="mail-bg" style="width: 100%;background-color: #f7fafc;text-align: center;">
            	<div style="padding: 20px; background-color: #fff;border-bottom: solid 1px #e0ebf2;">
            		<div class="logo">
             <img alt="OMS" src="/local/templates/kdteam/images/png/header/logo-oms.png" class="header__logo_img">
            		</div>
            	</div>
            	<div class="mail-contetn" style="padding: 70px 20px;max-width: 80%;margin: 0 auto;">
             <img src="/local/templates/kdteam/images/pages/home/Illustration3.svg" style="height: 500px;" alt="">
            		<h1 class="mail-contetn-title" style="font-size: 56px;text-align: center;margin-bottom: 50px;color: #186b9c;">
            		Здравствуйте! </h1>
            		<p class="mail-contetn-text" style="font-size: 21px;color: #202020;line-height: 36px;">
            			 Ваше обращение о возврате денежных средств направлено в адрес страховой компании для рассмотрения. В соответствии с действующим законодательством в течение <b>30 дней</b> вам должны предоставить информацию о рассмотрении обращения. Это может быть окончательный ответ по результатам рассмотрения обращения, либо уведомление о продлении срока рассмотрения обращения или о его переадресации (направлении на рассмотрение в иную организацию).
            		</p>
            	</div>
            </div>
            <br>
