app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

fos_user-security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_resetting_request:
    path: /resetting/request
    defaults: { _controller: AppBundle:User\Resetting:request }

fos_user_resetting_reference_outdated:
    path: /resetting/reference-outdated
    defaults: { _controller: AppBundle:User\Resetting:referenceOutdated }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

redcode_tree:
    resource: "@RedCodeTreeBundle/Resources/config/routing.yml"
    prefix:   /admin

article_show:
    path:      /{slug}
    defaults:  { _controller: AppBundle:Article:show }
