# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiToken: '%api_token%'
            $mailerFrom: '%mailer_from%'
            $mailerSenderName: '%mailer_sender_name%'
            $appealPathPdf: '%appeal_path_pdf%'
            $appealPathAttached: '%appeal_path_attached%'
            $smsPrivateKey: '%sms_private_key%'
            $smsPublicKey: '%sms_public_key%'
            $smsUrl: '%sms_url%'
            $smsProtocolVersion: '%sms_protocol_version%'


    _instanceof:
        Accurateweb\ClientApplicationBundle\DataAdapter\ClientApplicationModelAdapterInterface:
            tags: ['aw.client_application.adapter']

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Tests,Exception}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    AppBundle\Sluggable\SlugSubscriber:
        arguments:
            - '@accurateweb.slugifier.yandex'
            - '@validator'
        tags:
            - { name: doctrine.event_subscriber, connection: default }

#    twig.extension.EndingFormatter:
#        class: AppBundle\Twig\EndingFormatTwigExtension
#        tags:
#            - { name: twig.extension }

    AppBundle\Helper\GetMessFromBitrix:
        public: true

    AppBundle\EventListener\CompanyRatingAggregatorSubscriber:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'
        tags:
            - { name: "doctrine.event_subscriber" }

    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments:
            - "@knp_menu.factory"

    AppBundle\Helper\MenuBuilder:
        public: true

    aw.location.repository:
      class: 'AppBundle\Repository\Geo\RegionRepository'
      arguments:
        - '@doctrine'

    aw.location.resolver.default:
      class: AppBundle\Resolver\DefaultRegionResolver
      arguments:
        - '@aw.settings.manager'
        - '@AppBundle\Repository\Geo\RegionRepository'
      tags:
        - { name: aw.location.resolver, priority: -1 }

    AppBundle\Service\ContactUs\ContactUsMailer:
        public: true

    AppBundle\Service\Feedback\FeedbackMailer:
        public: true

    AppBundle\Service\Obrashcheniya\ObrashcheniaBranchMailer:
        public: true
        lazy: true

    AppBundle\Service\Obrashcheniya\ObrashcheniaUserMailer:
        public: true
        lazy: true

    AppBundle\Util\BitrixHelper:
        public: true
        lazy: true

    Accurateweb\EmailTemplateBundle\Email\Factory\EmailFactory:
      alias: aw_email_templating.template.factory
      lazy: true

    obrashcheniya_emails_service:
      class: AppBundle\Service\Rabbit\ObrashcheniyaEmailsService
      lazy: true

    obrashcheniya_files_service:
      class: AppBundle\Service\Rabbit\ObrashcheniyaFilesService
      lazy: true

    AppBundle\Entity\Company\Feedback:
        constraints:
            - Sonata\Form\Validator\Constraints\InlineConstraint:
                  service: sonata.page.cms.page
                  method: validateBlock

    AppBundle\Service\Sms\SmsAtomPark:
      public: true

    app.form.registration:
      class: AppBundle\Form\Profile\RegistrationFormType
      tags:
        - { name: form.type,  alias: "app_user_registration" }

    Accurateweb\ApplicationSettingsAdminBundle\Model\Manager\SettingManagerInterface:
      alias: aw.settings.manager
      public: true

    AppBundle\Service\UserMailer\Mailer:
      class: AppBundle\Service\UserMailer\Mailer
      decorates: fos_user.mailer
      arguments:
        - '@AppBundle\Service\UserMailer\Mailer.inner'
        - '@aw_email_templating.template.factory'
        - '%mailer_from%'
        - '%mailer_sender_name%'
        - '@aw.settings.manager'
        - '@mailer'
        - '@router'
        - '@templating'
        - {
          confirmation.template: '%fos_user.registration.confirmation.template%',
          resetting.template: '%fos_user.resetting.email.template%',
          from_email: { confirmation: '%fos_user.registration.confirmation.from_email%', resetting: '%fos_user.resetting.email.from_email%' } }
      tags:
        - { name: fos_user.requires_swift }