services:
  app.settings.region_default:
    class: AppBundle\Model\SettingConfiguration\SelectEntitySettingConfiguration
    arguments:
      - 'region_default'
      - '@AppBundle\Repository\Geo\RegionRepository'
      - 'Регион по умолчанию'
    tags:
      - { name: aw.setting.configuration }

  app.settings.agreement:
    class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\StringSettingConfiguration
    arguments:
      - 'agreement'
      - 'Адрес страницы с пользовательским соглашением'
      - ~
    tags:
      - { name: aw.setting.configuration }

  app.settings.personal_data:
    class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\StringSettingConfiguration
    arguments:
      - 'personal_data'
      - 'Адрес страницы с политикой по обработке персональных данных'
      - ~
    tags:
      - { name: aw.setting.configuration }

  app.settings.social_telegram:
    class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\StringSettingConfiguration
    arguments:
      - 'social_telegram'
      - 'Адрес чата в Telegram'
      - ~
    tags:
      - { name: aw.setting.configuration }

  app.settings.social_instagram:
    class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\StringSettingConfiguration
    arguments:
      - 'social_instagram'
      - 'Адрес страницы Instagram ленты'
      - ~
    tags:
      - { name: aw.setting.configuration }

  app.settings.default_email:
    class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\StringSettingConfiguration
    arguments:
      - 'default_email'
      - 'Email адрес по умолчанию'
      - 'noreply@bezbahil.ru'
    tags:
      - { name: aw.setting.configuration }

  app.settings.main_email:
    class: Accurateweb\ApplicationSettingsAdminBundle\Model\SettingConfiguration\StringSettingConfiguration
    arguments:
      - 'main_email'
      - 'Главный Email адрес'
      - 'info@bezbahil.ru'
    tags:
      - { name: aw.setting.configuration }