version: '3'

networks:
  default:
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 192.168.123.180/29
  frontend:
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 192.168.123.190/29
  backend:
    driver: ${NETWORKS_DRIVER}
    ipam:
      config:
        - subnet: 192.168.123.200/28

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  percona:
    driver: ${VOLUMES_DRIVER}
  mssql:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  memcached:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  neo4j:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  minio:
    driver: ${VOLUMES_DRIVER}
  rethinkdb:
    driver: ${VOLUMES_DRIVER}
  phpmyadmin:
    driver: ${VOLUMES_DRIVER}
  adminer:
    driver: ${VOLUMES_DRIVER}
  aerospike:
    driver: ${VOLUMES_DRIVER}
  caddy:
    driver: ${VOLUMES_DRIVER}
  elasticsearch:
    driver: ${VOLUMES_DRIVER}

services:
  nginx:
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
    volumes:
      - ${APP_CODE_PATH_HOST_SF}:${APP_CODE_PATH_CONTAINER_SF}
      - ${DATA_PATH_LOGS}/nginx:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_SITES_PATH}/bezbahil.local.conf:/etc/nginx/sites-available/bezbahil.local.conf
